var chart2 = new CanvasJS.Chart("chartContainer2",
{
  animationEnabled: true,
  backgroundColor: "dimgrey",     
  title:{
    text: "District Male/Female Percentage",
    fontColor: "Black"    
  },
  axisY: {
    title: "Male/Female Percent",
    titleFontColor: "Black",
    lineColor: "Black",  
    maximum: 1,
    gridThickness: 0  
  },
  axisX: {
    lineColor: "Black"  
  },       
  data: [
  {
    type: "bar",
    showInLegend: true,
    legendText: "Female",
    color: "red",
    dataPoints: [
    { y: 0.36, label: "District 1"},
    { y: 0.56, label: "District 2"},
    { y: 0.68, label: "District 3"},
    { y: 0.65, label: "District 4"},
    { y: 0.57, label: "District 5"},
    { y: 0.44, label: "District 6"},
    { y: 0.54, label: "District 7"},
    { y: 0.94, label: "District 8"},
    { y: 0.59, label: "District 9"},
    { y: 0.58, label: "District 10"},
    { y: 0.59, label: "District 11"},
    { y: 0.73, label: "District 12"},
    { y: 1, label: "District 13"},
    { y: 0.72, label: "District 14"},
    { y: 0.81, label: "District 15"},
    { y: 0, label: "District 16"},
    { y: 0.75, label: "District 17"},
    { y: 0.74, label: "District 18"},
    { y: 0, label: "District 19"},
    { y: 0.77, label: "District 20"},
    { y: 0.55, label: "District 21"},
    { y: 0.7, label: "District 22"},
    { y: 0, label: "District 23"},
    { y: 0.5, label: "District 24"},
    { y: 0.5, label: "District 25"},
    { y: 0, label: "District 26"},
    { y: 0.33, label: "District 27"},
    { y: 0.58, label: "District 28"},
    { y: 0.25, label: "District 29"},
    { y: 0.67, label: "District 30"},
    ]
  },
{
    type: "bar",
    showInLegend: true,
    legendText: "Male",
    color: "blue",
    dataPoints: [
    { y: 0.64, label: "District 1"},
    { y: 0.44, label: "District 2"},
    { y: 0.32, label: "District 3"},
    { y: 0.35, label: "District 4"},
    { y: 0.43, label: "District 5"},
    { y: 0.56, label: "District 6"},
    { y: 0.46, label: "District 7"},
    { y: 0.06, label: "District 8"},
    { y: 0.41, label: "District 9"},
    { y: 0.42, label: "District 10"},
    { y: 0.41, label: "District 11"},
    { y: 0.27, label: "District 12"},
    { y: 0, label: "District 13"},
    { y: 0.28, label: "District 14"},
    { y: 0.19, label: "District 15"},
    { y: 0, label: "District 16"},
    { y: 0.25, label: "District 17"},
    { y: 0.26, label: "District 18"},
    { y: 0, label: "District 19"},
    { y: 0.23, label: "District 20"},
    { y: 0.45, label: "District 21"},
    { y: 0.3, label: "District 22"}, 
    { y: 0, label: "District 23"},
    { y: 0.5, label: "District 24"},
    { y: 0.5, label: "District 25"},
    { y: 1, label: "District 26"},
    { y: 0.68, label: "District 27"},
    { y: 0.42, label: "District 28"},
    { y: 0.75, label: "District 29"},
    { y: 0.33, label: "District 30"},
    ]
    },
    ]
});

chart2.render();